"""Named placeholders for simulation constants retained from the legacy game."""

BOARD_WIDTH = None
BOARD_HEIGHT = None
MAX_ACTION_POINTS = None
MAX_DAMAGE = None
MAX_PATIENTS_LOST = None
PATIENTS_TO_EVACUATE = None
INITIAL_ENCOUNTER_COUNT = None
INITIAL_RAT_SWARM_COUNT = None
MAX_ENCOUNTERS = None
RAT_KING_LIMIT = None
RAT_SURGE_LIMIT = None
DOCTOR_START_POSITIONS = None
EXIT_POSITIONS = None
